window.language = {
    // Navigation
    "nav_home": { "fr": "Accueil", "pt": "Início" },
    "nav_about": { "fr": "À propos", "pt": "Sobre" },
    "nav_services": { "fr": "Services", "pt": "Serviços" },
    "nav_contact": { "fr": "Contact", "pt": "Contato" },

    // Header / Home
    "header_title": { "fr": "Bienvenue,<br>à<span> Althea.</span>", "pt": "Bem-vindo,<br>à<span> Althea.</span>" },
    "header_subtitle": { "fr": "Thérapies Intégrées pour Alana Moraes", "pt": "Terapias Integradas para Alana Moraes" },
    "header_desc1": {
        "fr": "<br><span>Althea</span>, du grec ancien, signifie « <span>guérison</span> ». C’est cette intention profonde qui guide chacune des thérapies proposées : offrir une approche intégrée du corps et de l’esprit, afin de permettre au corps de retrouver son fonctionnement optimal en respectant son intelligence naturelle.",
        "pt": "<br><span>Althea</span>, do grego antigo, significa \"<span>cura</span>\". É essa intenção profunda que guia cada uma das terapias propostas: oferecer uma abordagem integrada do corpo e da mente, de modo a permitir que o corpo recupere seu funcionamento ideal respeitando sua inteligência natural."
    },
    "header_desc2": {
        "fr": "<span>Le Pilates</span> agit directement sur le corps physique. À travers le renforcement musculaire, l’assouplissement et le travail postural, il favorise l’équilibre, la stabilité et la fluidité des mouvements.<br><br><span>La massothérapie</span> permet un travail plus profond sur les tensions musculaires et les mémoires corporelles. Par des techniques adaptées aux besoins de chaque personne, elle aide à relâcher les tensions physiques, à apaiser le système nerveux et à soutenir la libération des charges émotionnelles accumulées dans le corps.<br><br><span>L’aromathérapie</span>, grâce à l’utilisation ciblée des huiles essentielles, soutient l’harmonisation émotionnelle et mentale, tout en contribuant au bien-être physique.<br><br><span>L’auriculothérapie</span> complète cette approche globale en stimulant des points spécifiques de l’oreille, aidant à rétablir l’équilibre énergétique et à soutenir la santé dans sa globalité.<br><br>Chez <span>Althea</span>, chaque soin est pensé comme un espace de reconnexion — à soi, à son corps et à son propre pouvoir de guérison.",
        "pt": "O <span>Pilates</span> atua diretamente no corpo físico. Através do fortalecimento muscular, flexibilidade e trabalho postural, promove o equilíbrio, a estabilidade e a fluidez dos movimentos.<br><br>A <span>massoterapia</span> permite um trabalho mais profundo sobre as tensões musculares e memórias corporais. Através de técnicas adaptadas às necessidades de cada pessoa, ajuda a libertar as tensões físicas, acalmar o sistema nervoso e apoiar a libertação das cargas emocionais acumuladas no corpo.<br><br>A <span>aromaterapia</span>, graças ao uso direcionado de óleos essenciais, apoia a harmonização emocional e mental, contribuindo para o bem-estar físico.<br><br>A <span>auriculoterapia</span> completa esta abordagem global estimulando pontos específicos na orelha, ajudando a restaurar o equilíbrio energético e a apoiar a saúde como um todo.<br><br>Na <span>Althea</span>, cada cuidado é pensado como um espaço de reconexão — consigo mesmo, com seu corpo e com seu próprio poder de cura."
    },

    // About
    "about_title": { "fr": "A propos de <span>moi</span>", "pt": "Sobre <span>mim</span>" },
    "about_subtitle": { "fr": "PERMET-MOI DE ME PRÉSENTER", "pt": "PERMITA-ME ME APRESENTAR" },
    "about_desc1": {
        "fr": "Je m'appele Alana Moraes, je suis physiothérapeute diplômée au Brésil, avec une spécialização en acupuncture et Pilates.",
        "pt": "Meu nome é Alana Moraes, sou fisioterapeuta formada no Brasil, com especialização em acupuntura e Pilates."
    },
    "about_desc2": {
        "fr": "En arrivant au Québec, la vie d'immigrante avec une jeune fille à charge ne m'a pas permis de poursuivre ma carrière. Après quelques années et désormais bien établie ici, j'ai décidé de revenir à ma paixão : enseigner le Pilates et favoriser l'harmonie entre le corps et l'esprit.",
        "pt": "Ao chegar no Québec, a vida de imigrante com uma filha jovem não me permitiu continuar minha carreira. Depois de alguns anos e agora bem estabelecida aqui, decidi voltar à minha paixão: ensinar Pilates e promover a harmonia entre corpo e mente."
    },
    "about_desc3": {
        "fr": "Aujourd'hui, je suis membre de l'ANQ (Association des Naturothérapeutes du Québec) et aussi membre de l'AMQ (Association des Massothérapeutes du Québec) et j'ai créé Althea pour réunir mes competences et mes formations dans un projet qui me permet de travailler pleinement ici.",
        "pt": "Hoje, sou membro da ANQ (Associação dos Naturotererapeutas do Québec) e também membro da AMQ (Associação dos Massoterapeutas do Québec) e criei a Althea para reunir minhas competências e formações em um projeto que me permite trabalhar plenamente aqui."
    },
    "about_desc4": {
        "fr": "Toujours à la recherche de nouvelles specialités et de défis, je suis enthousiaste à l'idée de continuer à apprendre et à évoluer dans ce domaine magnifique.",
        "pt": "Sempre em busca de novas especialidades e desafios, estou entusiasmada com a ideia de continuar aprendendo e evoluindo neste campo magnífico."
    },

    // Formations
    "formations_title": { "fr": "Mes formations", "pt": "Minhas formações" },
    "lang_title": { "fr": "Langues parlées", "pt": "Idiomas falados" },

    // Services
    "services_title": { "fr": "Mes <span>Services</span>", "pt": "Meus <span>Serviços</span>" },
    "service_pilates": { "fr": "PILATES", "pt": "PILATES" },
    "service_massage": { "fr": "MASSAGE", "pt": "MASSAGEM" },
    "back": { "fr": "Retour", "pt": "Voltar" },
    "pilates_desc": {
        "fr": "Le <span>Pilates au sol</span> est une méthode complète et structurée qui vise le renforcement harmonieux du corps dans sa globalité. Basé sur le contrôle, la précision et la respiration, il permet de développer la stabilité, l’équilibre et la coordination des mouvements.<br><br>Cette pratique sollicite en profondeur les muscles stabilisateurs — notamment ceux du centre du corps (abdominaux profonds, plancher pelvien, muscles paravertébraux) — essentiels pour soutenir la colonne vertébrale et améliorer la posture au quotidien.<br><br>Le <span>Pilates au sol</span> contribue également à :<br>• Soulager les tensions musculaires et certaines douleurs chroniques<br>• Améliorer la mobilité articulaire et la souplesse<br>• Prévenir les blessures<br>• Favoriser une meilleure conscience corporelle<br><br>Au-delà du travail physique, il invite à une véritable connexion entre le corps et l’esprit. La concentration et la respiration consciente stimulent le système nerveux parasympathique, favorisant un état de calme, de présence et d’équilibre intérieur.<br><br>Chaque séance est adaptée aux besoins et aux capacités de la personne, dans une approche respectueuse, progressive et sécuritaire.",
        "pt": "O <span>Pilates solo</span> é um método completo e estruturado que visa o reforço harmonioso do corpo na sua globalidade. Baseado no controle, na precisão e na respiração, permite desenvolver a estabilidade, o equilíbrio e a coordenação dos movimentos.<br><br>Esta prática solicita em profundidade os músculos estabilizadores — nomeadamente os do centro do corpo (abdominais profundos, soalho pélvico, músculos paravertebrais) — essenciais para sustentar a coluna vertebral e melhorar a postura no dia-a-dia.<br><br>O <span>Pilates solo</span> contribui também para :<br>• Aliviar as tensões musculares e certas dores crónicas<br>• Melhorar a mobilidade articular e a flexibilidade<br>• Prevenir lesões<br>• Favorecer uma melhor consciência corporal<br><br>Para além do trabalho físico, convida a uma verdadeira conexão entre o corpo e a mente. A concentração e a respiração consciente estimulam o sistema nervoso parassimpático, favorecendo um estado de calma, presença e equilíbrio interior.<br><br>Cada sessão é adaptada às necessidades e capacidades da pessoa, numa abordagem respeitosa, progressiva e segura."
    },
    "pilates_schedule_title": { "fr": "Horaires et Durée", "pt": "Horários e Duração" },
    "pilates_schedule_desc": { "fr": "Cours de 50 minutes. Disponibilités du Lundi au Vendredi.", "pt": "Aulas de 50 minutos. Disponibilidades de segunda a sexta-feira." },
    "pilates_materials_title": { "fr": "Matériel", "pt": "Materiais" },
    "pilates_materials_desc": {
        "fr": "Découvrez les accessoires que nous utilisons pour enrichir votre pratique, améliorer votre posture et sculpter votre corps en profondeur :<br><br><b>L’Élastique (Theraband)</b> : Pour travailler la résistance et l'étirement musculaire en douceur.<br><br><b>La Mini-band</b> : Idéale pour intensifier le travail des fessiers et la stabilité des articulations.<br><br><b>Le Magic Circle (Cercle de Pilates)</b> : L'accessoire incontournable pour tonifier les bras, les cuisses et engager le centre du corps.<br><br><b>Le Rouleau (Cylindre)</b> : Parfait pour le travail d’équilibre, de massage des tissus et de mobilité de la colonne vertébrale.<br><br><b>Le Ballon (Swiss Ball)</b> : Pour solliciter les muscles stabilisateurs profonds grâce à l'instabilité.<br><br><b>Les Balles Lestées</b> : De petits poids sphériques pour renforcer le haut du corps tout en fluidité.<br><br><b>Les Haltères</b> : Pour un renforcement musculaire ciblé et progressif.<br><br><b>La Barre de Ballet</b> : Utilisée pour le travail de l'équilibre, de la posture et des jambes inspiré de la danse classique.<br><br><b>Exercices au Poids du Corps</b> : Parce que votre propre corps est votre meilleur outil pour gagner en force et en souplesse.",
        "pt": "Descubra os acessórios que utilizamos para enriquecer a sua prática, melhorar a sua postura e esculpir o seu corpo em profundidade:<br><br><b>O Elástico (Theraband)</b>: Para trabalhar a resistência e o alongamento muscular com suavidade.<br><br><b>A Mini-band</b>: Ideal para intensificar o trabalho dos glúteos e a estabilidade das articulações.<br><br><b>O Magic Circle (Círculo de Pilates)</b>: O acessório indispensável para tonificar os braços, as coxas e trabalhar o centro do corpo.<br><br><b>O Rolo (Cilindro)</b>: Perfeito para o trabalho de equilíbrio, massagem dos tecidos e mobilidade da coluna vertebral.<br><br><b>A Bola (Swiss Ball)</b>: Para exercitar os músculos estabilizadores profundos através da instabilidade.<br><br><b>As Bolas de Peso</b>: Pequenos pesos esféricos para fortalecer a parte superior do corpo com fluidez.<br><br><b>Os Halteres</b>: Para um reforço muscular direcionado e progressivo.<br><br><b>A Barra de Ballet</b>: Utilizada para o trabalho de equilíbrio, postura e pernas, inspirado na dança clássica.<br><br><b>Exercícios com o Peso do Corpo</b>: Porque o seu próprio corpo é a sua melhor ferramenta para ganhar força e flexibilidade."
    },
    "book_trial": { "fr": "Réserver une séance d'essai", "pt": "Marcar aula experimental" },
    "m_drenagem": { "fr": "Drenage Lymphatique", "pt": "Drenagem Linfática" },
    "m_detente": { "fr": "Massage Détente", "pt": "Massagem Relaxante" },
    "m_terapeutica_detalhes": { "fr": "Massage Thérapeutique (60 ou 90 min)", "pt": "Massagem Terapêutica (60 ou 90 min)" },
    "m_reiki": { "fr": "Reiki", "pt": "Reiki" },
    "m_auriculo": { "fr": "Auriculoacupuncture", "pt": "Auriculoacupuntura" },
    "massage_explanation": {
        "fr": "La massothérapie est bien plus qu'un moment de détente ; c'est une approche globale qui agit en synergie sur vos dimensions physiques et énergétiques pour restaurer l'équilibre naturel de votre organisme.<br><br><b>Une Action Physique Profonde</b><br>Sur le plan structurel, le massage travaille directement sur les tissus mous et le système musculosquelettique. Ses bénéfices incluent :<br><br>• <b>Relâchement Musculaire</b> : Élimination des tensions et des nœuds (points gâchettes) accumulés par le stress ou la posture.<br>• <b>Amélioration de la Circulation</b> : Stimulation du flux sanguin et lymphatique, favorisant l'oxygénation des tissus et l'élimination des toxines.<br>• <b>Souplesse Articulaire</b> : Amélioration de l'amplitude de mouvement en redonnant de l'élasticité aux fascias et aux muscles.",
        "pt": "A massoterapia é muito mais do que um momento de relaxamento; é uma abordagem global que atua em sinergia sobre as suas dimensões físicas e energéticas para restaurar o equilíbrio natural do seu organismo.<br><br><b>Uma Ação Física Profunda</b><br>No plano estrutural, a massagem trabalha diretamente sobre os tecidos moles e o sistema musculoesquelético. Seus benefícios incluem:<br><br>• <b>Relaxamento Muscular</b> : Eliminação de tensões e nós (pontos gatilho) acumulados pelo estresse ou postura.<br>• <b>Melhoria da Circulação</b> : Estimulação do fluxo sanguíneo e linfático, favorecendo a oxigenação dos tecidos e a eliminação de toxinas.<br>• <b>Flexibilidade Articular</b> : Melhoria da amplitude de movimento ao devolver a elasticidade às fáscias e aos músculos."
    },
    "m_detente_desc": {
        "fr": "Le <span>massage détente</span> est une véritable parenthèse de douceur conçue pour apaiser le système nerveux et libérer les tensions accumulées au quotidien. À travers des mouvements fluides, enveloppants et rythmés, ce soin invite votre corps et votre esprit à un lâcher-prise total.<br><br><b>Pourquoi choisir le massage détente ?</b><br>• <b>Réduction du Stress</b> : Calme instantanément l'agitation mentale et abaisse le niveau de cortisol (l'hormone du stress).<br>• <b>Amélioration du Sommeil</b> : Prépare le corps à un repos profond et réparateur en favorisant la production d'endorphines.<br>• <b>Harmonie Corporelle</b> : Redonne une sensation de légèreté et de fluidité à l'ensemble du corps, de la tête aux pieds.<br>• <b>Évasion Sensorielle</b> : Un momento sacré pour se reconnecter à ses sens et retrouver une paix intérieure durable.",
        "pt": "A <span>massagem relaxante</span> é um verdadeiro parêntese de suavidade concebido para acalmar o sistema nervoso e libertar as tensões acumuladas diariamente. Através de movimentos fluidos, envolventes e rítmicos, este cuidado convida o seu corpo e a sua mente a uma entrega total.<br><br><b>Porquê escolher a massagem relaxante?</b><br>• <b>Redução do Estresse</b> : Acalma instantaneamente a agitação mental e reduz o nível de cortisol (a hormona do estresse).<br>• <b>Melhoria do Sono</b> : Prepara o corpo para um descanso profundo e reparador ao favorecer a produção de endorfinas.<br>• <b>Harmonia Corporal</b> : Devolve uma sensação de leveza e fluidez a todo o corpo, da cabeça aos pés.<br>• <b>Evasão Sensorial</b> : Um momento sagrado para se reconectar com os seus sentidos e reencontrar uma paz interior duradoura."
    },
    "book_now": { "fr": "Réserver", "pt": "Reservar" },
    "m_drenagem_desc": {
        "fr": "Le <span>drainage lymphatique</span> est une technique de massage douce et rythmée qui stimule la circulation de la lymphe et soutient le bon fonctionnement du système lymphatique.<br><br>Le système lymphatique joue un rôle essentiel dans l’élimination des toxines, le soutien du système immunitaire et la régulation des liquides dans le corps. Lorsque sa circulation est ralentie, il peut y avoir sensation de jambes lourdes, gonflement, rétention d’eau ou fatigue.<br><br>Grâce à des mouvements lents, précis et adaptés, le <span>drainage lymphatique</span> aide à :<br>• Réduire la rétention d’eau et les gonflements<br>• Améliorer la circulation<br>• Soutenir le système immunitaire<br>• Favoriser la détoxification naturelle du corps<br>• Apporter une sensation profonde de légèreté et de bien-être<br><br>Au-delà des bienfaits physiques, cette technique agit également sur le système nerveux, favorisant la relaxation et l’équilibre intérieur.",
        "pt": "A <span>drenagem linfática</span> é uma técnica de massagem suave e rítmica que estimula a circulação da linfa e apoia o bom funcionamento do sistema linfático.<br><br>O sistema linfático desempenha um papel essencial na eliminação de toxinas, no apoio ao sistema imunitário e na regulação dos líquidos no corpo. Quando a sua circulação é abrandada, pode haver sensação de pernas pesadas, inchaço, retenção de líquidos ou fadiga.<br><br>Graças a movimentos lentos, precisos e adaptados, a <span>drenagem linfática</span> ajuda a :<br>• Reduzir a retenção de líquidos e os inchaços<br>• Melhorar a circulação<br>• Apoiar o sistema imunitário<br>• Favorecer a desintoxicação natural do corpo<br>• Proporcionar uma sensação profunda de leveza e de bem-estar<br><br>Para além dos benefícios físicos, esta técnica atua também no sistema nervoso, favorecendo o relaxamento e o equilíbrio interior."
    },
    "m_terapeutica_desc": {
        "fr": "La <span>massothérapie thérapeutique</span> proposée chez Althea est une approche intégrée qui unit techniques musculaires, stimulation énergétique et relaxation profonde.<br><br>Chaque séance est personnalisée selon les besoins physiques et émotionnels du moment. Le soin peut combiner différentes techniques afin d’agir à plusieurs niveaux : musculaire, nerveux et énergétique.<br><br>✧ Techniques utilisées :<br><br><b>Massage Deep Tissue</b><br>Travail en profondeur sur les tensions musculaires chroniques, les adhérences et les zones de douleur persistante. Il favorise la libération des tissus, améliore la mobilité et soutient la récupération musculaire.<br><br><b>Massage Relaxant</b><br>Manœuvres fluides et enveloppantes qui apaisent le système nerveux, diminuent le stress et invitent à un état de détente profonde.<br><br><b>Ventouses (cupping therapy)</b><br>Utilisées pour stimuler la circulation sanguine et lymphatique, relâcher les fascias et aider à dénouer les tensions profondes.<br><br><b>Diapasons thérapeutiques (Tuning Forks)</b><br>Appliqués sur des points spécifiques du corps, ils utilisent les vibrations sonores pour soutenir l’équilibre énergétique et favoriser une harmonisation subtile du système nerveux.<br><br><b>Huiles essentielles</b><br>Sélectionnées avec soin, elles accompagnent le travail corporel en soutenant la détente musculaire, l’équilibre émotionnel et le bien-être global.<br><br><b>Cristaux</b><br>Utilisés comme support énergétique, ils participent à l’harmonisation du champ vibratoire et à la création d’un espace de soin profondément apaisant.",
        "pt": "A <span>massoterapia terapêutica</span> proposta na Althea é uma abordagem integrada que une técnicas musculares, estimulação energética e relaxamento profundo.<br><br>Cada sessão é personalizada segundo as necessidades físicas e emocionais do momento. O cuidado pode combinar diferentes técnicas a fim de atuar a vários níveis: muscular, nervoso e energético.<br><br>✧ Técnicas utilizadas :<br><br><b>Massagem Deep Tissue</b><br>Trabalho em profundidade nas tensões musculares crónicas, nas aderências e nas zonas de dor persistente. Favorece a libertação dos tecidos, melhora a mobilidade e apoia a recuperação muscular.<br><br><b>Massagem Relaxante</b><br>Manobras fluidas e envolventes que acalmam o sistema nervoso, diminuem o stress e convidam a um estado de relaxamento profundo.<br><br><b>Ventosas (cupping therapy)</b><br>Utilizadas para estimular a circulação sanguínea e linfática, relaxar as fáscias e ajudar a desfazer as tensões profundas.<br><br><b>Diapasões terapêuticos (Tuning Forks)</b><br>Aplicados em pontos específicos do corpo, utilizam as vibrações sonoras para apoiar o equilíbrio energético e favorecer uma harmonização subtil do sistema nervoso.<br><br><b>Óleos essenciais</b><br>Selecionados com cuidado, acompanham o trabalho corporal apoiando o relaxamento muscular, o equilíbrio emocional e o bem-estar global.<br><br><b>Cristais</b><br>Utilizados como suporte energético, participam na harmonização do campo vibratório e na criação de um espaço de cuidado profundamente calmante."
    },
    "m_reiki_desc": {
        "fr": "Le <span>Reiki</span> est une approche énergétique d’origine japonaise qui vise à rétablir l’harmonie naturelle entre le corps, les émotions et l’esprit.<br><br>Lors d’une séance de Reiki Niveau I, la personne reste habillée et confortablement installée sur la table de soin. Le praticien applique les mains délicatement sur différentes zones du corps ou légèrement au-dessus, permettant à l’énergie de circuler là où elle est nécessaire.<br><br>Le <span>Reiki</span> agit principalement sur le système énergétique, en soutenant l’équilibre des chakras — centres énergétiques situés le long de la colonne vertébrale. Chaque chakra est associé à des aspects physiques, émotionnels et psychiques :<br><br>• <b>Chakra racine</b> : sécurité, stabilité, ancrage<br>• <b>Chakra sacré</b> : émotions, créativité<br>• <b>Plexus solaire</b> : confiance, pouvoir personnel<br>• <b>Chakra du cœur</b> : amour, relations<br>• <b>Chakra de la gorge</b> : communication<br>• <b>Troisième œil</b> : intuition<br>• <b>Chakra couronne</b> : connexion spirituelle<br><br>Lorsque l’énergie circule librement, le corps active naturellement ses mécanismes d’autorégulation.<br><br>Une séance peut aider à :<br>• Réduire le stress et l’anxiété<br>• Favoriser un état de relaxation profonde<br>• Soutenir l’équilibre émotionnel<br>• Améliorer la qualité du sommeil<br>• Apporter une sensation d’harmonisation globale",
        "pt": "O <span>Reiki</span> é uma abordagem energética de origem japonesa que visa restabelecer a harmonia natural entre o corpo, as emoções e a mente.<br><br>Durante uma sessão de Reiki Nível I, a pessoa permanece vestida e confortavelmente instalada na mesa de tratamento. O praticante aplica as mãos delicadamente em diferentes zonas do corpo ou ligeiramente acima, permitindo que a energia circule onde é necessária.<br><br>O <span>Reiki</span> atua principalmente no sistema energético, apoiando o equilíbrio dos chakras — centros energéticos situados ao longo da coluna vertebral. Cada chakra está associado a aspetos físicos, emocionais e psíquicos:<br><br>• <b>Chakra raiz</b>: segurança, estabilidade, enraizamento<br>• <b>Chakra sacro</b>: emoções, criatividade<br>• <b>Plexo solar</b>: confiança, poder pessoal<br>• <b>Chakra do coração</b>: amor, relações<br>• <b>Chakra da garganta</b>: comunicação<br>• <b>Terceira visão</b>: intuição<br>• <b>Chakra coroa</b>: conexão espiritual<br><br>Quando a energia circula livremente, o corpo ativa naturalmente os seus mecanismos de autorregulação.<br><br>Uma sessão pode ajudar a :<br>• Reduzir o stress e a ansiedade<br>• Favorecer um estado de relaxamento profundo<br>• Apoiar o equilíbrio emocional<br>• Melhorar a qualidade do sono<br>• Proporcionar uma sensação de harmonização global"
    },
    "m_auriculo_desc": {
        "fr": "L’auriculo-acupuncture est une technique thérapeutique qui consiste à stimuler des points spécifiques situés sur l’oreille, considérée comme une représentation réflexe du corps entier.<br><br>En agissant sur ces points à l’aide d’aiguilles fines ou de stimulations adaptées, cette approche vise à soutenir l’équilibre énergétique, à soulager certaines douleurs et à accompagner la régulation du stress et des émotions.<br><br>Douce et personnalisée, l’auriculo-acupuncture s’intègre harmonieusement aux autres thérapies proposées, dans une vision globale du bien-être.",
        "pt": "A auriculoacupuntura é uma técnica terapêutica que consiste em estimular pontos específicos situados na orelha, considerada como uma representação reflexa de todo o corpo.<br><br>Ao atuar sobre esses pontos com agulhas finas ou estímulos adaptados, esta abordagem visa apoiar o equilíbrio energético, aliviar certas dores e acompanhar a regulação do estresse e das emoções.<br><br>Suave e personalizada, a auriculoacupuntura integra-se harmoniosamente com as outras terapias propostas, numa visão global do bem-estar."
    },

    // Contact
    "contact_title": { "fr": "Contactez <span>Moi</span>", "pt": "Me <span>Contactar</span>" },

    // Timeline / Education
    "edu_aec": { "fr": "Conception et Programmation de sites web", "pt": "Concepção e Programação de sites web" },
    "edu_reiki": { "fr": "Reiki Niveau I", "pt": "Reiki Nível I" },
    "edu_pilates": { "fr": "Pilates machines et Matt", "pt": "Pilates máquinas e Solo (Matt)" },
    "edu_acu": { "fr": "Acupuncture et auriculopuncture", "pt": "Acupuntura e auriculopuntura" },
    "edu_physio": { "fr": "Physiothérapie", "pt": "Fisioterapia" },

    // Contact Form
    "form_name": { "fr": "Nom", "pt": "Nome" },
    "form_email": { "fr": "Email", "pt": "Email" },
    "form_phone": { "fr": "Téléphone", "pt": "Telefone" },
    "form_message": { "fr": "Message", "pt": "Mensagem" },
    "form_submit": { "fr": "Envoyer", "pt": "Enviar" },
    "disclaimer_note": {
        "fr": "Veuillez noter que les séances de massage et les cours de Pilates proposés ont pour but exclusif la relaxation, le bien-être général et le renforcement musculaire. En aucun cas, ces services ne remplacent un diagnostic, un avis ou un traitement médical. Si vous souffrez de douleurs persistantes, de blessures ou de conditions de santé particulières, il est impératif de consulter un médecin ou un professionnel de la santé qualifié avant de commencer toute activité. L’utilisation de nos services ne doit jamais retarder une consultation médicale.",
        "pt": "Por favor, note que as sessões de massagem e as aulas de Pilates propostas têm como objetivo exclusivo o relaxamento, o bem-estar geral e o fortalecimento muscular. Em caso algum estes serviços substituem um diagnóstico, um conselho ou um tratamento médico. Se sofre de dores persistentes, lesões ou condições de saúde particulares, é imperativo consultar um médico ou um profissional de saúde qualificado antes de iniciar qualquer atividade. A utilização dos nossos serviços nunca deve atrasar uma consulta médica."
    "edu_title_certification": { "fr": "CERTIFICATION", "pt": "CERTIFICAÇÃO" },
        "edu_title_aec": { "fr": "AEC", "pt": "AEC" },
        "edu_title_pilates": { "fr": "FORMATION EN PILATES", "pt": "FORMAÇÃO EM PILATES" },
        "edu_title_acu": { "fr": "SPÉCIALISATION EN ACUPUNCTURE", "pt": "ESPECIALIZAÇÃO EM ACUPUNTURA" },
        "edu_title_physio": { "fr": "BACCALAURÉAT", "pt": "GRADUAÇÃO" }
    };

// check localstorage
// if dont exist create default to 'en' ( parse json )
// based on the lang choosed save a variable called lang with the value ( en or fr)
// let lang = 'en'
// language.greetings[lang]